export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_DASHNAV = "TOGGLE_DASHNAV";

export const GET_PROFILE_BEGIN = "GET_PROFILE_BEGIN";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_SUBMIT = "HANDLE_SUBMIT";
export const HANDLE_CHANGE = "  HANDLE_CHANGE";
export const HANDLE_SELECT_CHANGE = "HANDLE_SELECT_CHANGE";
export const HANDLE_SELECT_SORT_CHANGE = "HANDLE_SELECT_SORT_CHANGE";
export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const GET_AUTHOR_POST_BEGIN = "GET_AUTHOR_POST_BEGIN";
export const GET_AUTHOR_POST_SUCCESS = "GET_AUTHOR_POST_SUCCESS";
export const GET_AUTHOR_POST_ERROR = "GET_AUTHOR_POST_ERROR";

export const GET_AUTHOR_SINGLE_POST_SUCCESS = "GET_AUTHOR_SINGLE_POST_SUCCESS";
export const GET_AUTHOR_SINGLE_POST_BEGIN = "GET_AUTHOR_SINGLE_POST_BEGIN";
export const GET_AUTHOR_SINGLE_POST_ERROR = "GET_AUTHOR_SINGLE_POST_ERROR";

export const CLEAR_AUTHOR_SINGLE_POST = "CLEAR_AUTHOR_SINGLE_POST";

export const POST_ID = "  POST_ID";
export const SET_EDIT_POST = "SET_EDIT_POST";
export const CLEAR_VALUES = "CLEAR_VALUES";
export const EDIT_POST_BEGIN = "EDIT_POST_BEGIN";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";

export const DELETE_POST_BEGIN = "DELETE_POST_BEGIN";
export const SET_EDIT_USER = "SET_EDIT_USER";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const CHANGE_PAGE = "CHANGE_PAGE"
