export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR"


export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR"

export const LOGOUT_USER = "LOGOUT_USER"

export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_DASHNAV = "TOGGLE_DASHNAV";

export const GET_PROFILE_BEGIN = "GET_PROFILE_BEGIN";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR"

export const HANDLE_SUBMIT = "HANDLE_SUBMIT"

export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR"


export const GET_AUTHOR_POST_BEGIN = "GET_AUTHOR_POST_BEGIN";
export const GET_AUTHOR_POST_SUCCESS = "GET_AUTHOR_POST_SUCCESS";
export const GET_AUTHOR_POST_ERROR = "GET_AUTHOR_POST_ERROR"