export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";


export const USER_R_TOKEN = "USER_R_TOKEN";


export const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
export const TOGGLE_DASHNAV = "TOGGLE_DASHNAV";

export const GET_PROFILE_BEGIN = "GET_PROFILE_BEGIN";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const HANDLE_SUBMIT = "HANDLE_SUBMIT";
export const HANDLE_CHANGE = "  HANDLE_CHANGE";
export const HANDLE_SELECT_CHANGE = "HANDLE_SELECT_CHANGE";
export const HANDLE_SELECT_SORT_CHANGE = "HANDLE_SELECT_SORT_CHANGE";
export const HANDLE_CHANGE_TAG = "  HANDLE_CHANGE_TAG";
export const HANDLE_CHANGE_NAV = "HANDLE_CHANGE_NAV"
export const HANDLE_SELECT_CHANGE_TAG = "HANDLE_SELECT_CHANGE_TAG";
export const HANDLE_SELECT_SORT_CHANGE_TAG = "HANDLE_SELECT_SORT_CHANGE_TAG";

export const CREATE_POST_BEGIN = "CREATE_POST_BEGIN";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const GET_AUTHOR_POST_BEGIN = "GET_AUTHOR_POST_BEGIN";
export const GET_AUTHOR_POST_SUCCESS = "GET_AUTHOR_POST_SUCCESS";
export const GET_AUTHOR_POST_ERROR = "GET_AUTHOR_POST_ERROR";

export const GET_AUTHOR_SINGLE_POST_BEGIN = "GET_AUTHOR_SINGLE_POST_BEGIN";
export const GET_AUTHOR_SINGLE_POST_SUCCESS = "GET_AUTHOR_SINGLE_POST_SUCCESS";
export const GET_AUTHOR_SINGLE_POST_ERROR = "GET_AUTHOR_SINGLE_POST_ERROR";

export const CLEAR_AUTHOR_SINGLE_POST = "CLEAR_AUTHOR_SINGLE_POST";

export const POST_ID = "  POST_ID";
export const COMMENT_ID = "COMMENT_ID";
export const COMMENT_REPLY_ID = "COMMENT_REPLY_ID";
export const SET_EDIT_POST = "SET_EDIT_POST";

export const CLEAR_VALUES = "CLEAR_VALUES";
export const CLEAR_SEARCH_VALUES = "CLEAR_SEARCH_VALUES";

export const EDIT_POST_BEGIN = "EDIT_POST_BEGIN";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";

export const EDIT_COMMENT_BEGIN = "EDIT_COMMENT_BEGIN";
export const EDIT_COMMENT_SUCCESS = "EDIT_COMMENT_SUCCESS";
export const EDIT_COMMENT_ERROR = "EDIT_COMMENT_ERROR";

export const EDIT_COMMENT_REPLY_BEGIN = "EDIT_COMMENT_REPLY_BEGIN";
export const EDIT_COMMENT_REPLY_SUCCESS = "EDIT_COMMENT_REPLY_SUCCESS";
export const EDIT_COMMENT_REPLY_ERROR = "EDIT_COMMENT_REPLY_ERROR";

export const DELETE_POST_BEGIN = "DELETE_POST_BEGIN";
export const DELETE_COMMENT_BEGIN = "DELETE_COMMENT_BEGIN";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";
export const DELETE_COMMENT_REPLY_BEGIN = "DELETE_COMMENT_REPLY_BEGIN";
export const DELETE_COMMENT_REPLY_SUCCESS = "DELETE_COMMENT_REPLY_SUCCESS";
export const DELETE_COMMENT_REPLY_ERROR = "DELETE_COMMENT_REPLY_ERROR";

export const SET_EDIT_USER = "SET_EDIT_USER";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const GET_TAGS_SEARCH_POST_BEGIN = "GET_TAGS_SEARCH_POST_BEGIN";
export const GET_TAGS_SEARCH_POST_SUCCESS = "GET_TAGS_SEARCH_POST_SUCCESS";
export const GET_TAGS_SEARCH_POST_ERROR = "GET_TAGS_SEARCH_POST_ERROR";

export const GET_NAV_SEARCH_POST_BEGIN = "GET_TAGS_SEARCH_POST_BEGIN";
export const GET_NAV_SEARCH_POST_SUCCESS = "GET_TAGS_SEARCH_POST_SUCCESS";
export const GET_NAV_SEARCH_POST_ERROR = "GET_TAGS_SEARCH_POST_ERROR";

export const GET_ALL_POST_BEGIN = "GET_ALL_POST_BEGIN";
export const GET_ALL_POST_SUCCESS = "GET_ALL_POST_SUCCESS";
export const GET_ALL_POST_ERROR = "GET_ALL_POST_ERROR";


export const GET_SAVED_POST_BEGIN = "GET_SAVED_POST_BEGIN";
export const GET_SAVED_POST_SUCCESS = "GET_SAVED_POST_SUCCESS";
export const GET_SAVED_POST_ERROR = "GET_SAVED_POST_ERROR";

export const GET_SINGLE_POST_BEGIN = "GET_SINGLE_POST_BEGIN";
export const GET_SINGLE_POST_SUCCESS = "GET_SINGLE_POST_SUCCESS";
export const GET_SINGLE_POST_ERROR = "GET_SINGLE_POST_ERROR";

export const GET_AUTHOR_PAGE_BEGIN = "GET_AUTHOR_PAGE_BEGIN";
export const GET_AUTHOR_PAGE_SUCCESS = "GET_AUTHOR_PAGE_SUCCESS";
export const GET_AUTHOR_PAGE_ERROR = "GET_AUTHOR_PAGE_ERROR";

export const POST_LIKES = " POST_LIKES";
export const POST_DISLIKES = "POST_DISLIKES";

export const COMMENT_LIKES = "COMMENT_LIKES";
export const COMMENT_DISLIKES = "COMMENT_DISLIKES";

export const COMMENT_REPLY_LIKES = "COMMENT_REPLY_LIKES";
export const COMMENT_REPLY_DISLIKES = "COMMENT_REPLY_DISLIKES";

export const TOGGLE_LIKE_BTN = "TOGGLE_LIKE_BTN";
export const TOGGLE_DISLIKE_BTN = "TOGGLE_DISLIKE_BTN";
export const TOGGLE_COMMENT_SECTION = "TOGGLE_COMMENT_SECTION";
export const TOGGLE_COMMENT_LIKE_BTN = "TOGGLE_COMMENT_LIKE_BTN";
export const TOGGLE_COMMENT_DISLIKE_BTN = "TOGGLE_COMMENT_DISLIKE_BTN";
export const TOGGLE_SAVE_BTN = "TOGGLE_SAVE_BTN";
export const TOGGLE_DELETE_MODAL_BTN = "TOGGLE_DELETE_MODAL_BTN";
export const TOGGLE_DELETECR_MODAL_BTN = "TOGGLE_DELETECR_MODAL_BTN";
export const TOGGLE_DELETEPT_MODAL_BTN = "TOGGLE_DELETEPT_MODAL_BTN";

export const SAVE_POST = "SAVE_POST";
export const UNSAVE_POST = "UNSAVE_POST";

export const CREATE_COMMENT_BEGIN = "CREATE_COMMENT_BEGIN";
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_ERROR = "CREATE_COMMENT_ERROR";

export const CREATE_COMMENT_REPLY_BEGIN = "CREATE_COMMENT_REPLY_BEGIN";
export const CREATE_COMMENT_REPLY_SUCCESS = "CREATE_COMMENT_REPLY_SUCCESS";
export const CREATE_COMMENT_REPLY_ERROR = "CREATE_COMMENT_REPLY_ERROR";

export const GET_COMMENT_BEGIN = "GET_COMMENT_BEGIN";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_ERROR = "GET_COMMENT_ERROR";


export const GET_CURRENT_USER_BEGIN = "GET_CURRENT_USER";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR";



export const GET_USER_STATS_BEGIN = "GET_USER_STATS_BEGIN";
export const GET_USER_STATS_SUCCESS = "GET_USER_STATS_SUCCESS";
export const GET_USER_STATS_ERROR = "GET_USER_STATS_ERROR";
